apiVersion: v1
kind: Pod
metadata:
  name: test-pod3
  annotations:
    k8s.v1.cni.cncf.io/networks: demo-network
spec:
  containers:
  - name: test-container3
    image: busybox
    ports:
    - containerPort: 20
    command: ["sh", "-c", "sleep 3600"]
