apiVersion: v1
kind: ServiceAccount
metadata:
  name: cni-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cni-manager
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cni-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cni-manager
subjects:
  - kind: ServiceAccount
    name: cni-manager
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cni-manager
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cni-manager
  template:
    metadata:
      labels:
        app: cni-manager
        component: network-controller  # Add more specific label
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: cni-manager
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - cni-manager
            topologyKey: kubernetes.io/hostname
      containers:
        - name: manager
          image: localhost:5000/cni-manager:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: run
              mountPath: /var/run
            - name: cni-socket-dir
              mountPath: /var/run/cni
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
      priorityClassName: system-node-critical
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoSchedule
      volumes:
        - name: run
          hostPath:
            path: /var/run
        - name: cni-socket-dir
          hostPath:
            path: /var/run/cni
            type: DirectoryOrCreate
