apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    network.policy: "restricted" # This will trigger network restrictions
spec:
  containers:
    - name: nginx
      image: nginx:alpine
